# python docker image
# Use the official Python image from the Docker Hub
FROM python:3.9-bookworm

# Set environment variables to prevent Python from writing pyc files to disk 
# and to buffer output (useful for Docker logs)
# ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1


# Set the working directory in the container
WORKDIR /blog_application

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Run the Django development server
# CMD python.manage.py runserver 0.0.0.0:8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]